baseUrl = "https://peromage.github.io"
title = "undefined behavior"

disqusShortname = ""
googleAnalytics = ""

languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
hasCJKLanguage = true

[author]
name = "Fang Deng"

[pagination]
pagerSize = 20
