#+hugo_base_dir: ../hugo
#+hugo_section: /
#+hugo_type: page
#+setupfile: ./setup.conf

Hugo site navigation page setup.

* PUBLISHED License
:PROPERTIES:
:EXPORT_FILE_NAME: license
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :toc false
:END:
:LOGBOOK:
- State "PUBLISHED"  from "CREATED"    [2022-11-16 Wed 19:52]
- State "CREATED"    from              [2022-11-16 Wed 19:39]
:END:
This website and its content are licensed under the [[https://github.com/peromage/peromage.github.io/blob/master/LICENSE][GNU General Public License v3.0]].

This website is built with [[https://www.gnu.org/software/emacs/][Emacs]], [[https://orgmode.org/][Org Mode]], [[https://gohugo.io/][Hugo]], [[https://ox-hugo.scripter.co/][ox-hugo]] and [[https://github.com/dschrempf/skeria][Skeria]].  Please refer to these projects' home page for licenses.

* PUBLISHED Privacy
:PROPERTIES:
:EXPORT_FILE_NAME: privacy
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :toc false
:END:
:LOGBOOK:
- State "PUBLISHED"  from "CREATED"    [2022-11-16 Wed 19:57]
- State "CREATED"    from              [2022-11-16 Wed 19:52]
:END:
** Privacy Notice
This website does not collect any data from you.

However, this website is themed with [[https://github.com/dschrempf/skeria][Skeria]] which loads some external resources and scripts.

If you have concerns, please visit its home page for more information.

* PUBLISHED Search
:PROPERTIES:
:EXPORT_FILE_NAME: search
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :layout search
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :outputs '(html json)
:END:
:LOGBOOK:
- State "PUBLISHED"  from "DRAFT"      [2022-06-05 Mon 01:12]
- State "CREATED"    from              [2022-06-05 Mon 01:12]
:END:

* PUBLISHED About
:PROPERTIES:
:EXPORT_FILE_NAME: about
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :toc false
:END:
:LOGBOOK:
- State "PUBLISHED"  from "DRAFT"      [2022-06-05 Mon 01:12]
- State "CREATED"    from              [2022-06-05 Mon 01:12]
:END:
** Me
Hi there.  This is Fang.

I'm currently a C++ developer working with one of the well-known automotive companies.

I have hair.  A lot.

Emacser.  Former Vimmer.

Oh most importantly, happy wife happy life.  :)

** Contact
Email: fang(at)saffyyre.com

Github: https://github.com/peromage

